### ISSUE TITLE
Duplicate App IDs

### ISSUE THREAD

**Issue by ericmccullough** [4n6k/Jump_List_AppIDs#2]
When processing the list I came across 3 duplicates:

5d696d521de238c3 = Google Chrome 48.0.2564.116 AND Chrome 9.0.597.84 / 12.0.742.100 / 13.0.785.215
319f01bf9fe00f2d = Microsoft Access 2016 64-bit AND Microsoft Access 2013 64-bit
6d2bac8f1edf6668 = Microsoft Outlook 2016 64-bit AND Microsoft Outlook 2013 32-bit

Thanks for compiling the list!

**Comment by 4n6k** [comment]
Thank you, Eric. Combined Chrome entries into one. Put Access/Outlook versions next to each other. Keeping Access/Outlook entries separate due to different default installation paths. However, moved them next to each other so it's easier to notice the difference.
